<?php

/**
 * @file
 * Contains eventbrite_events.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function eventbrite_events_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the eventbrite_events module.
    case 'help.page.eventbrite_events':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add event and attendee entities from Eventbrite') . '</p>';
      return $output;

    default:
  }
}
